# Generated by Django 5.0.3 on 2024-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receipent',
            new_name='recipient',
        ),
    ]
